local _, ns = ...

-- Auto-generated by scripts/generate_font_catalog.sh.
-- Re-run this script after adding/removing files in Media/.
ns.FontCatalog = {
    list = {
        { key = "DelugiaMonoCompleteBold", label = "Delugia Mono Complete Bold", path = "Interface\\AddOns\\mummuFrames\\Media\\DelugiaMonoCompleteBold.ttf" },
        { key = "DepartureMonoNerdFontMono_Regular", label = "Departure Mono Nerd Font Mono Regular", path = "Interface\\AddOns\\mummuFrames\\Media\\DepartureMonoNerdFontMono-Regular.otf" },
        { key = "Gilroy_Heavy", label = "Gilroy Heavy", path = "Interface\\AddOns\\mummuFrames\\Media\\Gilroy-Heavy.ttf" },
        { key = "Lexend_wght_", label = "Lexend", path = "Interface\\AddOns\\mummuFrames\\Media\\Lexend[wght].ttf" },
        { key = "ProductSans_Bold", label = "Product Sans Bold", path = "Interface\\AddOns\\mummuFrames\\Media\\ProductSans-Bold.ttf" },
        { key = "RobotoMono_Bold", label = "Roboto Mono Bold", path = "Interface\\AddOns\\mummuFrames\\Media\\RobotoMono-Bold.ttf" },
        { key = "SIFONN_PRO", label = "SIFONN PRO", path = "Interface\\AddOns\\mummuFrames\\Media\\SIFONN_PRO.otf" },
        { key = "expressway", label = "Expressway", path = "Interface\\AddOns\\mummuFrames\\Media\\expressway.ttf" },
    },
}
