local _, ns = ...

-- Auto-generated by scripts/generate_font_catalog.sh.
-- Re-run this script after adding/removing files in Fonts/.
ns.FontCatalog = {
    list = {
        { key = "expressway", label = "Expressway", path = "Interface\\AddOns\\mummuFrames\\Fonts\\expressway.ttf" },
        { key = "Fredoka_SemiBold", label = "Fredoka Semi Bold", path = "Interface\\AddOns\\mummuFrames\\Fonts\\Fredoka-SemiBold.ttf" },
    },
}
