#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MEDIA_DIR="$ROOT_DIR/Media"
OUT_FILE="$ROOT_DIR/Core/FontCatalog.lua"

if [[ ! -d "$MEDIA_DIR" ]]; then
  echo "Media directory not found: $MEDIA_DIR" >&2
  exit 1
fi

label_from_filename() {
  local name="$1"
  name="${name%.*}"
  name="${name//_/ }"
  name="${name//-/ }"
  name="$(sed -E 's/([a-z0-9])([A-Z])/\1 \2/g' <<<"$name")"
  name="$(sed -E 's/\[[^]]+\]//g' <<<"$name")"
  name="$(sed -E 's/[[:space:]]+/ /g; s/^ //; s/ $//' <<<"$name")"
  name="$(awk '{for (i = 1; i <= NF; i++) { if ($i ~ /^[A-Z0-9]+$/) { w = $i } else { w = toupper(substr($i, 1, 1)) tolower(substr($i, 2)) } printf "%s%s", (i > 1 ? " " : ""), w } printf "\n"}' <<<"$name")"
  printf '%s' "$name"
}

key_from_filename() {
  local name="$1"
  name="${name%.*}"
  name="${name//[^A-Za-z0-9]/_}"
  printf '%s' "$name"
}

mapfile -t font_files < <(find "$MEDIA_DIR" -maxdepth 2 -type f \( -iname '*.ttf' -o -iname '*.otf' \) | sort)

{
  echo "local _, ns = ..."
  echo
  echo "-- Auto-generated by scripts/generate_font_catalog.sh."
  echo "-- Re-run this script after adding/removing files in Media/."
  echo "ns.FontCatalog = {"
  echo "    list = {"

  for file in "${font_files[@]}"; do
    rel_path="${file#"$ROOT_DIR/"}"
    wow_path="Interface\\\\AddOns\\\\mummuFrames\\\\${rel_path//\//\\\\}"
    base_name="$(basename "$file")"
    label="$(label_from_filename "$base_name")"
    key="$(key_from_filename "$base_name")"

    printf '        { key = "%s", label = "%s", path = "%s" },\n' "$key" "$label" "$wow_path"
  done

  echo "    },"
  echo "}"
} > "$OUT_FILE"

echo "Generated $OUT_FILE with ${#font_files[@]} fonts."
